import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/providers/themeProvider";

export const metadata: Metadata = {
  title: "Team Management",
  icons: "/auth-images/icon.png",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          disableTransitionOnChange
          defaultTheme="dark"
          enableSystem
        >
          <ClerkProvider> {children}</ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
